name: actions
on: [push]
jobs:
  build:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v4
		- uses: actions/setup-java@v4
	  	with:
				distribution: 'oracle' # See 'Supported distributions' for available options
	  		java-version: '17'
	  	name: "Gradle"
		- run: ./gradlew

	  	name: "Build"
		- run: ./gradlew build